### ISSUE TITLE
Show user-friendly messages when dealing with OPML errors

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#81]
java.lang.Exception: Can't parse OPML file: getAttributeValue(null, Symbols.TEXT) must not be null
	at feeds.FeedsViewModel$importFeeds$2.invokeSuspend(FeedsViewModel.kt:60)
	at feeds.FeedsViewModel$importFeeds$2.invoke(Unknown Source:10)
	at feeds.FeedsViewModel.changeState(FeedsViewModel.kt:133)
	at feeds.FeedsViewModel.importFeeds(FeedsViewModel.kt:54)
	at feeds.FeedsFragment$importFeedsLauncher$1$1$1.invokeSuspend(FeedsFragment.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NullPointerException: getAttributeValue(null, Symbols.TEXT) must not be null
	at opml.OpmlKt.importOpml(Opml.kt:49)
	at feeds.FeedsViewModel$importFeeds$2.invokeSuspend(FeedsViewModel.kt:58)
	... 10 more

**Comment by bubelov** [comment]
It's fixed in the master branch, leaving this issue open to verify after release

**Comment by Donkey-Doug** [comment]
I downloades the latest debug version. Still cannot import OPML.

![Screenshot_20211005-145610_News_Debug](https://user-images.githubusercontent.com/50382414/136026959-dc998449-70f4-45bf-945a-09c08443c993.png)

**Comment by bubelov** [comment]
@Donkey-Doug I think this OPML file is invalid. `TEXT` is a mandatory element, every OPML item should have it

**Comment by Donkey-Doug** [comment]
Github won't let me upload it. How do you recommend I share the file?

**Comment by bubelov** [comment]
Got it, here is the list:

```xml
<?xml version="1.0" encoding="utf-8"?>
<opml version="2.0">
  <head>
    <dateCreated>Tue, 05 Oct 2021 15:08:22 GMT</dateCreated>
    <docs />
  </head>
  <body>
    <outline type="rss" title="Tweakers" xmlUrl="http://www.tweakers.net/feeds/nieuws.xml" />
    <outline type="rss" title="Notebookcheck" xmlUrl="https://www.notebookcheck.net/RSS-Feed-All-Articles-EN.165552.0.html" />
    <outline type="rss" title="NOS" xmlUrl="http://www.nos.nl/nos/rss/nieuws.xml" />
    <outline type="rss" title="UltrabookReview" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCgRUqKlyEohtMeceU6Am_QA" />
    <outline type="rss" title="PhoneArena" xmlUrl="http://www.phonearena.com/feed" />
    <outline type="rss" title="OMG! Ubuntu!" xmlUrl="http://feeds.feedburner.com/d0od" />
    <outline type="rss" title="GSMArena" xmlUrl="http://www.gsmarena.com/rss-news-reviews.php3" />
    <outline type="rss" title="The Verge" xmlUrl="http://www.theverge.com/rss/full.xml" />
    <outline type="rss" title="r/Android" xmlUrl="http://www.reddit.com/r/Android/.rss" />
    <outline type="rss" title="r/Fossdroid" xmlUrl="https://www.reddit.com/r/fossdroid/.rss" />
    <outline type="rss" title="r/Apple" xmlUrl="http://www.reddit.com/r/apple/.rss" />
    <outline type="rss" title="Alex on Autos" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UC3qM33hHgedfi7qTKKgIApg" />
    <outline type="rss" title="Itemp Plays" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCxE76PmXA8V_5wHOWGpRrmA" />
    <outline type="rss" title="Linus Tech Tips" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw" />
    <outline type="rss" title="Andrew Marc David" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCqh8w-GY6v0vgwIn_iWt87A" />
    <outline type="rss" title="Dave Lee" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCVYamHliCI9rw1tHR1xbkfw" />
    <outline type="rss" title="The Tech Chap" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCzlXf-yUIaOpOjEjPrOO9TA" />
    <outline type="rss" title="Just Josh" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCtHm9ai5zSb-yfRnnUBopAg" />
    <outline type="rss" title="This Week in GNOME" xmlUrl="https://thisweek.gnome.org/index.xml" />
    <outline type="rss" title="Jellyfin blog" xmlUrl="https://jellyfin.org/index.xml" />
  </body>
</opml>
```

**Comment by bubelov** [comment]
@Donkey-Doug here is the spec:

http://opml.org/spec2.opml

> Text attribute

> Every outline element must have at least a text attribute, which is what is displayed when an outliner opens the OPML file. To omit the text attribute would render the outline useless in an outliner. This is what the user would see -- clearly an unacceptable user experience. Part of the purpose of producing OPML is to give users the power to accumulate and organize related information in an outliner. This is as important a use for OPML as data interchange.

> A missing text attribute in any outline element is an error

It looks like this OPML is invalid, it should use `text` element but it uses `title` instead

**Comment by bubelov** [comment]
This website can validate OPML files and it also confirms that this feed is invalid: http://validator.opml.org/

@Donkey-Doug I think some other apps have less strict validation rules, this app strives to strictly follow the spec. You can probably use any of those apps to import this invalid OPML and then use them to export valid OPML for you. Flym is the issue here, it should work just fine if you create your OPML with any other app

> I also cannot manually add some feeds. Example: http://www.nos.nl/nos/rss/nieuws.xml

I'll move this to a separate issue

**Comment by bubelov** [comment]
Fixed in https://github.com/bubelov/news/commit/17836162f9f46b324d7875f9347c655cefff5550
